export const orderType = {
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE: "GET_ORDER_FAILURE",

    PATCH_ORDER_ACCEPT_REQUEST: "PATCH_ORDER_ACCEPT_REQUEST",
    PATCH_ORDER_ACCEPT_SUCCESS: "PATCH_ORDER_ACCEPT_SUCCESS",
    PATCH_ORDER_ACCEPT_FAILURE: "PATCH_ORDER_ACCEPT_FAILURE",

    PATACH_CANCLE_ORDER_REQUEST: "PATACH_CANCLE_ORDER_REQUEST",
    PATACH_CANCLE_ORDER_SUCCESS: "PATACH_CANCLE_ORDER_SUCCESS",
    PATACH_CANCLE_ORDER_FAILURE: "PATACH_CANCLE_ORDER_FAILURE"

}