export const productType = {
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

    PATCH_PRODUCT_STAUTS_REQUEST: "PATCH_PRODUCT_STAUTS_REQUEST",
    PATCH_PRODUCT_STAUTS_SUCCESS: "PATCH_PRODUCT_STAUTS_SUCCESS",
    PATCH_PRODUCT_STAUTS_FAILURE: "PATCH_PRODUCT_STAUTS_FAILURE",

    CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",

    PATCH_PRODUCT_REQUEST: "PATCH_PRODUCT_REQUEST",
    PATCH_PRODUCT_SUCCESS: "PATCH_PRODUCT_SUCCESS",
    PATCH_PRODUCT_FAILURE: "PATCH_PRODUCT_FAILURE",

    PRODUCT_CLEAR_ERROR: "PRODUCT_CLEAR_ERROR"
}